language: rust

sudo: required

dist: trusty

addons:
  apt:
    packages:
      - libssl-dev
      - redis-server

cache: cargo

rust:
  - stable

before_cache: |
  cargo install cargo-tarpaulin

script:
  - cargo build
  - cargo tarpaulin --out Xml

after_success: |
    # create and upload a report for codecov.io
    bash <(curl -s https://codecov.io/bash)