language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
      - redis-server
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
  fi

script:
  - cargo clean
  - cargo build
  - cargo test -- --nocapture

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    # create and upload a report for codecov.io
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi