[package]
name = "redis-event"
version = "0.1.0"
authors = ["maplestoria <zkx6648@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.2"

[dev-dependencies]
serial_test = "0.3.2"